### ISSUE TITLE
Plugin Breaks all builds if not properly configured

### ISSUE THREAD

**Issue by dchristensen** [vyadh/teamcity-azure-keyvault-plugin#1]
I installed the plugin and it immediately made it so none of my builds work.  They all fail with the generic error `Failed to start build`.  I believe its because I haven't configured the plugin yet, but probably shouldn't break the build server just by installing the plugin.  Here's the stack trace:
````
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.github.vyadh.teamcity.keyvault.server.AzureAccessTokenPasswordProvider.findSecret(AzureAccessTokenPasswordProvider.kt:36)
	at com.github.vyadh.teamcity.keyvault.server.AzureAccessTokenPasswordProvider.getPasswordParameters(AzureAccessTokenPasswordProvider.kt:15)
	at jetbrains.buildServer.serverSide.parameters.types.PasswordsSearcher.collectPasswords(PasswordsSearcher.java:8)
	at jetbrains.buildServer.serverSide.parameters.types.PasswordsBuildStartContextProcessor.updateParameters(PasswordsBuildStartContextProcessor.java:6)
	at jetbrains.buildServer.serverSide.impl.RunningBuildImpl.prepareRunners(RunningBuildImpl.java:447)
	at jetbrains.buildServer.serverSide.impl.RunningBuildImpl.createAgentBuild(RunningBuildImpl.java:800)
	at jetbrains.buildServer.serverSide.impl.BuildStarter$1.run(BuildStarter.java:8)
	at jetbrains.buildServer.serverSide.impl.BuildStarter$2$1.run(BuildStarter.java:3)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
	at jetbrains.buildServer.serverSide.impl.BuildStarter$2.run(BuildStarter.java:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
````

**Comment by vyadh** [comment]
Completely didn't occur to me to test this obvious (at least, in hindsight) scenario. The company I work for is using it in a new TeamCity instance which is probably why it didn't come up.

Anyway, thanks for the report. I'll fix this.

**Comment by vyadh** [comment]
This was slightly different to what I originally assumed - builds would only work if the plugin connection was installed at the same level or above the build in the project hierarchy. That definitely used to work, but it appears I broke it by making last minute changes. That'll teach me!

Anyway, fixed now. I'll resubmit to Jetbrains plugin portal.
