### ISSUE TITLE
Could not fetch Azure token

### ISSUE THREAD

**Issue by cuntoulishifu** [vyadh/teamcity-azure-keyvault-plugin#6]
I get error as below when use the plugin:

Error fetching Azure access token: Could not fetch Azure token, received response code 400 for url: https://login.microsoftonline.com/xxxxxxxx-47f2-4355-a6a1-xxxxxxxx/oauth2/token: com.github.vyadh.teamcity.keyvault.common.KeyVaultException: Could not fetch Azure token, received response code 400 for url: https://login.microsoftonline.com/xxxxxxxx-47f2-4355-a6a1-xxxxxxxx/oauth2/token, see teamcity-server.log for details

Cloud you help me ?

Thanks!

**Comment by vyadh** [comment]
Do you have a proxy in the way of your TeamCity server?

Perhaps you could have a look at the teamcity-server.log and paste any relevant details here?

**Comment by cuntoulishifu** [comment]
Thanks for reply!

I test the agent,it can get token with powersehll REST Api

`$postParams = @{grant_type='client_credentials';client_id='xxxxxxxx-7b3f-4ae5-a5f3-xxxxxxxxx';client_secret='xxxxxxxxxxxxxxxx';resource='https://management.azure.com/'}
$res=Invoke-WebRequest -Uri https://login.microsoftonline.com/xxxxxxxxxx-47f2-4355-a6a1-xxxxxxxxxx/oauth2/token -Method POST -Body $postParams`

teamcity-server.log as below:

`[2019-12-24 09:06:09,565]   INFO - ity.BuildQueuePriorityOrdering - New item Queued build {item id=6179, promotion=Build promotion {promotion id=6179, configuration={id=demo_BoLI_AzureBillingReportAutomationUpload_Test, internal id=bt402}}} with weight 0.00 inserted at the default position 0 in the end of the queue
[2019-12-24 09:06:09,606]   INFO - s.buildServer.ACTIVITIES.AUDIT - build_add_to_queue: Build BUILD_PROMOTION{id=6179} was added to queue by "'aabw6zz' (Bo Li CW) {id=150}"
[2019-12-24 09:06:09,626]   INFO - tbrains.buildServer.ACTIVITIES - Build added to queue; Queued build {Build promotion {promotion id=6179, configuration={id=demo_BoLI_AzureBillingReportAutomationUpload_Test, internal id=bt402}, queued}, triggered by "'aabw6zz' (Bo Li CW) {id=150}" (##userId='150' type='user')}
[2019-12-24 09:06:09,678]   INFO -   jetbrains.buildServer.SERVER - Running build saved to DB: build id=6179, promotion id=6179
[2019-12-24 09:06:09,678]   INFO - tbrains.buildServer.ACTIVITIES - Build started; zDemo / BoLI / AzureBillingReportAutomationUpload / test {id=demo_BoLI_AzureBillingReportAutomationUpload_Test, internal id=bt402} #71 {promotion id=6179, agent="CNODC06" {id=4}, triggered by "'aabw6zz' (Bo Li CW) {id=150}" (##userId='150' type='user'). Started 2019-12-24 09:06:09.643, running}
[2019-12-24 09:06:09,687]   INFO -   jetbrains.buildServer.SERVER - Build removed from queue (started): 6179
[2019-12-24 09:06:09,697]   INFO -   jetbrains.buildServer.SERVER - Flush queue finished in 62ms, number of builds started: 1
[2019-12-24 09:06:10,981]   WARN - zureBuildStartContextProcessor - Error fetching Azure access token: Could not fetch Azure token, received response code 400 for url: https://login.microsoftonline.com/xxxxxxxx-47f2-4355-a6a1-xxxxxxxxxx/oauth2/token
com.github.vyadh.teamcity.keyvault.common.KeyVaultException: Could not fetch Azure token, received response code 400 for url: https://login.microsoftonline.com/xxxxxxxx-47f2-4355-a6a1-xxxxxxxxxx/oauth2/token
	at com.github.vyadh.teamcity.keyvault.server.AzureTokenConnector.executeRequest(AzureTokenConnector.kt:46)
	at com.github.vyadh.teamcity.keyvault.server.AzureTokenConnector.requestToken(AzureTokenConnector.kt:34)
	at com.github.vyadh.teamcity.keyvault.server.AzureBuildStartContextProcessor.updateParametersWithToken(AzureBuildStartContextProcessor.kt:71)
	at com.github.vyadh.teamcity.keyvault.server.AzureBuildStartContextProcessor.updateParameters(AzureBuildStartContextProcessor.kt:32)
	at jetbrains.buildServer.serverSide.impl.RunningBuildImpl.prepareRunners(RunningBuildImpl.java:325)
	at jetbrains.buildServer.serverSide.impl.RunningBuildImpl.createAgentBuild(RunningBuildImpl.java:65)
	at jetbrains.buildServer.serverSide.impl.BuildStarter.startBuild(BuildStarter.java:108)
	at jetbrains.buildServer.serverSide.impl.BuildStarter.lambda$null$0(BuildStarter.java:199)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
	at jetbrains.buildServer.serverSide.impl.BuildStarter.lambda$startBuildAsync$1(BuildStarter.java:23)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[2019-12-24 09:06:17,298]   INFO -   jetbrains.buildServer.SERVER - Build finished received for build: #71 {build id=6179, buildTypeId=demo_BoLI_AzureBillingReportAutomationUpload_Test}
[2019-12-24 09:06:17,310]   INFO -   jetbrains.buildServer.SERVER - Created finish build task for build: #71 {build id=6179, buildTypeId=demo_BoLI_AzureBillingReportAutomationUpload_Test}, task id: 1557
[2019-12-24 09:06:17,335]   INFO -   jetbrains.buildServer.SERVER - Build scheduled for finishing: #71 {build id=6179, buildTypeId=demo_BoLI_AzureBillingReportAutomationUpload_Test}
[2019-12-24 09:06:17,335]   INFO -   jetbrains.buildServer.SERVER - Start execution of build finishing: #71 {build id=6179, buildTypeId=demo_BoLI_AzureBillingReportAutomationUpload_Test}
[2019-12-24 09:06:17,403]   INFO - ndexer.EventBasedBuildsIndexer - Indexing finishing build: #71 {build id=6179, buildTypeId=demo_BoLI_AzureBillingReportAutomationUpload_Test}
[2019-12-24 09:06:17,441]   INFO - de.impl.history.DBBuildHistory - Created build history entry; build id: 6179, finish date: 2019-12-24 09:06:17.255
[2019-12-24 09:06:17,462]   INFO - tbrains.buildServer.ACTIVITIES - Finished build zDemo / BoLI / AzureBillingReportAutomationUpload / test {id=demo_BoLI_AzureBillingReportAutomationUpload_Test, internal id=bt402} #71 {promotion id=6179, agent="CNODC06" {id=4}, triggered by "'aabw6zz' (Bo Li CW) {id=150}" (##userId='150' type='user'). Started 2019-12-24 09:06:13.090, finished. Status "FAILURE 'Error fetching Azure access token: Could not fetch Azure token, received response code 400 for url: https://login.microsoftonline.com/xxxxxxxx-47f2-4355-a6a1-xxxxxxxxxx/oauth2/token: com.github.vyadh.teamcity.keyvault.common.KeyVaultException: Coul...'"}
[2019-12-24 09:07:16,369]   INFO -   jetbrains.buildServer.SERVER - Build finished received for build: #1 {build id=6178, buildTypeId=utilities_DbMigrationFromIdcToSqlmiProd_Ccmmto_ToProd}
[2019-12-24 09:07:16,379]   INFO -   jetbrains.buildServer.SERVER - Created finish build task for build: #1 {build id=6178, buildTypeId=utilities_DbMigrationFromIdcToSqlmiProd_Ccmmto_ToProd}, task id: 1558
[2019-12-24 09:07:16,404]   INFO -   jetbrains.buildServer.SERVER - Build scheduled for finishing: #1 {build id=6178, buildTypeId=utilities_DbMigrationFromIdcToSqlmiProd_Ccmmto_ToProd}
[2019-12-24 09:07:16,404]   INFO -   jetbrains.buildServer.SERVER - Start execution of build finishing: #1 {build id=6178, buildTypeId=utilities_DbMigrationFromIdcToSqlmiProd_Ccmmto_ToProd}
[2019-12-24 09:07:16,460]   INFO - ndexer.EventBasedBuildsIndexer - Indexing finishing build: #1 {build id=6178, buildTypeId=utilities_DbMigrationFromIdcToSqlmiProd_Ccmmto_ToProd}
[2019-12-24 09:07:16,492]   INFO - de.impl.history.DBBuildHistory - Created build history entry; build id: 6178, finish date: 2019-12-24 09:07:16.304
[2019-12-24 09:07:16,514]   INFO - tbrains.buildServer.ACTIVITIES - Finished build Utilities / DB Migration from IDC to SQLMI Prod / CCMMTO / To PROD {id=utilities_DbMigrationFromIdcToSqlmiProd_Ccmmto_ToProd, internal id=bt442} #1 {promotion id=6178, agent="cncicd01-agent02" {id=5}, triggered by "'a9k47zz' (Carl Sun) {id=5}" (##userId='5' type='user'). Started 2019-12-24 09:04:21.119, finished. Status "NORMAL 'Running'"}
[2019-12-24 09:10:01,104]   WARN -     jetbrains.buildServer.AUTH - Error occurred during HTTP authentication while processing request GET '/app/rest/server', from client 127.0.0.1 ([0:0:0:0:0:0:0:1]:60290), user-agent "YouTrack/2019.2 (build #53938). Base URL: https://cnyt.xxxxxxxx.com", no auth: jetbrains.buildServer.serverSide.auth.AuthenticationFailedException: Incorrect username or password. (enable debug to see stacktrace)
[2019-12-24 09:20:01,104]   WARN -     jetbrains.buildServer.AUTH - Error occurred during HTTP authentication while processing request GET '/app/rest/server', from client 127.0.0.1 ([0:0:0:0:0:0:0:1]:37592), user-agent "YouTrack/2019.2 (build #53938). Base URL: https://cnyt.xxxxxxxx.com", no auth: jetbrains.buildServer.serverSide.auth.AuthenticationFailedException: Incorrect username or password. (enable debug to see stacktrace)`

**Comment by cuntoulishifu** [comment]
Thanks for your reply!

I thik I'd found the issue, because in Connection parameter I type 'https://{mykeyvalt}.vault.azure.net/' .
And when type 'https://vault.azure.net' I successfully got the Azure Token.

**Comment by vyadh** [comment]
Great, glad you found the problem.
